### ISSUE TITLE
Message screens show grid pattern

### ISSUE THREAD

**Issue by pedropsi** [Narkhos/Puzzlescript-Wrapper#1]
This happened with [unlucky unlock](https://pedropsi.github.io/unlucky-unlock#lfodp)

![imagem](https://user-images.githubusercontent.com/36260325/66413517-6d329d80-e9ef-11e9-96c0-a1847a393f7d.png)

**Comment by pedropsi** [comment]
Also with [hastefulll](https://pedropsi.github.io/hastefulll#lfodp)

![img](https://user-images.githubusercontent.com/36260325/66413928-4a54b900-e9f0-11e9-9b2e-8bf554db893f.png)

**Comment by Narkhos** [comment]
Ok, I forgot to update opengl clear color according to backgroundcolor on changing game. It will be fixed in the next release.

**Comment by pedropsi** [comment]
It's fixed - thank you!
